// User Session
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGOUT_SUCCESSFUL = 'LOGOUT_SUCCESSFUL';
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';
export const UPDATE_USER_AVATAR = 'UPDATE_USER_AVATAR';
export const UPDATE_NOTIFICATIONS_NUMBER = 'UPDATE_NOTIFICATIONS_NUMBER';
export const UPDATE_GLOBAL_NOTIFICATIONS = 'UPDATE_GLOBAL_NOTIFICATIONS';
// Real Estate
export const CREATE_REAL_ESTATE = 'CREATE_REAL_ESTATE';
export const EDIT_REAL_ESTATE = 'EDIT_REAL_ESTATE';
export const UPDATE_REAL_ESTATE = 'UPDATE_REAL_ESTATE';
export const CLEAR_ESTATE = 'CLEAR_ESTATE';
// Search
export const UPDATE_ADDRESS_LINE = 'UPDATE_ADDRESS_LINE';
export const UPDATE_SEARCH_FILTER = 'UPDATE_SEARCH_FILTER';
export const UPDATE_SEARCH_RESULT = 'UPDATE_SEARCH_RESULT';
export const UPDATE_SEARCH_TYPE = 'UPDATE_SEARCH_TYPE';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
